version: "3.9"

networks:
  appnet:
    driver: bridge

services:
  yii2-db:
    image: mysql:8.0
    container_name: yii2-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: yii2advanced
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: Europe/Moscow
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - appnet

  yii2-app:
    build:
      context: ..
      dockerfile: ./docker/php-fpm/Dockerfile
    container_name: yii2-app
    volumes:
      - ../:/var/www/html
    env_file:
      - ../.env
    depends_on:
      - yii2-db
    networks:
      - appnet

  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - yii2-app
    networks:
      - appnet

volumes:
  mysql_data:
